# Generated by Django 5.2.2 on 2025-06-09 12:49

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0013_historicalclinic_historicalclinicslot_and_more'),
        ('participants', '0011_alter_appointment_clinic_slot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAppointment',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('DID_NOT_ATTEND', 'Did not attend'), ('CHECKED_IN', 'Checked in'), ('SCREENED', 'Screened'), ('PARTIALLY_SCREENED', 'Partially screened'), ('ATTENDED_NOT_SCREENED', 'Attended not screened')], default='CONFIRMED', max_length=50)),
                ('reinvite', models.BooleanField(default=False)),
                ('stopped_reasons', models.JSONField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('clinic_slot', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clinics.clinicslot')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('screening_episode', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='participants.screeningepisode')),
            ],
            options={
                'verbose_name': 'historical appointment',
                'verbose_name_plural': 'historical appointments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalParticipant',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('gender', models.TextField()),
                ('nhs_number', models.TextField()),
                ('phone', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('ethnic_group', models.CharField(blank=True, choices=[('English, Welsh, Scottish, Northern Irish or British', 'English, Welsh, Scottish, Northern Irish or British'), ('Irish', 'Irish'), ('Gypsy or Irish Traveller', 'Gypsy or Irish Traveller'), ('Any other White background', 'Any other White background'), ('White and Black Caribbean', 'White and Black Caribbean'), ('White and Black African', 'White and Black African'), ('White and Asian', 'White and Asian'), ('Any other mixed or multiple ethnic background', 'Any other mixed or multiple ethnic background'), ('Indian', 'Indian'), ('Pakistani', 'Pakistani'), ('Bangladeshi', 'Bangladeshi'), ('Chinese', 'Chinese'), ('Any other Asian background', 'Any other Asian background'), ('African', 'African'), ('Caribbean', 'Caribbean'), ('Any other Black, African or Caribbean background', 'Any other Black, African or Caribbean background'), ('Arab', 'Arab'), ('Any other ethnic group', 'Any other ethnic group'), ('Prefer not to say', 'Prefer not to say')], null=True)),
                ('risk_level', models.TextField()),
                ('extra_needs', models.JSONField(blank=True, default=list)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical participant',
                'verbose_name_plural': 'historical participants',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalScreeningEpisode',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='participants.participant')),
            ],
            options={
                'verbose_name': 'historical screening episode',
                'verbose_name_plural': 'historical screening episodes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
